kind: pipeline
name: default

steps:

  - name: nexusPublish
    image: nexus.admin.sharecare.com/drone-nexus-docker
    settings:
      version: cat ./version
    privileged: true

  - name: deployQa
    image: nexus.admin.sharecare.com/drone-kubernetes-deploy:testh
    settings:
      version: cat ./version
      namespace: qa
