kind: pipeline
name: default

steps:

  - name: nexusPublish
    image: nexus.admin.sharecare.com/drone-nexus-docker
    settings:
      version: 1
    privileged: true

  - name: deployQa
    image: nexus.admin.sharecare.com/drone-kubernetes-deploy
    settings:
      version: 1
      namespace: qa
